version: "3"
services:
  bewegungsmelderbot:
    image: docker.pkg.github.com/alwinius/tummensabot/bewegungsmelderbot:latest
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "127.0.0.1:4215:4215"
    volumes:
      - ${PWD}/bewegungsmelder.sqlite:/app/bewegungsmelder.sqlite
      - ${PWD}/config.ini:/app/config.ini
  watchtower:
    image: containrrr/watchtower:0.3.9
    restart: always
    environment:
      - REPO_USER=${GITHUB_USER}
      - REPO_PASS=${GITHUB_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable