# environment variables are resolved from the .env file (which is not part of the git repository)
version: "3"
services:
  bewegungsmelderbot:
    image: docker.pkg.github.com/alwinius/bewegungsmelder-telegram/bewegungsmelderbot:latest
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "127.0.0.1:${PORT}:8080"
    volumes:
      - ${PWD}/bewegungsmelder.sqlite:/app/bewegungsmelder.sqlite
      - ${PWD}/config.ini:/app/config.ini
      - /etc/localtime:/etc/localtime:ro # this is to get local time within the container
  watchtower:
    image: containrrr/watchtower:0.3.9
    restart: always
    environment:
      - REPO_USER=${GITHUB_USER}
      - REPO_PASS=${GITHUB_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable